added tag to version verification to cd pipelines

diff --git a/.github/workflows/rook_sdk_health_connect_cd.yml b/.github/workflows/rook_sdk_health_connect_cd.yml
--- a/.github/workflows/rook_sdk_health_connect_cd.yml
+++ b/.github/workflows/rook_sdk_health_connect_cd.yml
@@ -26,6 +26,29 @@ jobs:
           flutter-version: 3.27.4
       - run: flutter --version
 
+      - name: Check versions match
+        run: |
+          # Extract version from tag (e.g., rook_sdk_health_connect-v1.2.3 -> 1.2.3)
+          # GITHUB_REF_NAME holds the tag name that triggered the workflow
+          TAG_VERSION=$(echo $GITHUB_REF_NAME | sed 's/rook_sdk_health_connect-v//')
+          
+          # Define the path to the pubspec.yaml file
+          PUBSPEC_PATH="packages/rook_sdk_health_connect/pubspec.yaml"
+          
+          # Extract version from pubspec.yaml (finds the line starting with 'version: ')
+          PUBSPEC_VERSION=$(grep '^version: ' $PUBSPEC_PATH | awk '{print $2}')
+          
+          echo "Git Tag Version: $TAG_VERSION"
+          echo "Pubspec Version: $PUBSPEC_VERSION"
+          
+          # Compare the two versions and fail the job if they don't match
+          if [ "$TAG_VERSION" != "$PUBSPEC_VERSION" ]; then
+            echo "Error: Git tag version ($TAG_VERSION) does not match pubspec.yaml version ($PUBSPEC_VERSION)."
+            exit 1
+          fi
+          
+          echo "Versions match! Proceeding with publish."
+
       - name: Install dependencies
         run: flutter pub get
         working-directory: packages/rook_sdk_health_connect
